# Generated by Django 4.0.4 on 2023-02-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Itracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='user',
        ),
    ]
