# Generated by Django 4.0.1 on 2022-04-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linksaver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksmodel',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
