# Generated by Django 4.0.4 on 2023-02-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('timeEvent', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('publisher', models.CharField(max_length=500)),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='searchSavedEvents',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
                ('eventDate', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('online', models.BooleanField(default=False)),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
